bases <- c("Rais","CadUnico")
file.name <- c("rais_2","cad_unico2")
dir.input <- c("rais","cad_unico")
dir.output <- c("consolidadas/rais", "consolidadas/cad_unico")
d <- data.frame(bases=bases, file_name=file.name, dir_input=dir.input, dir_output=dir.output)
